### ISSUE TITLE
如果使用  $form->tab('技术参数', function (Form $form) {}）不起作用

### ISSUE THREAD

**Issue by loveyuxiao** [zuweie/FieldInteraction#11]
如果使用  $form->tab('技术参数', function (Form $form) {
 $form->select('group_id', $this->FieldColumn['group_id']);
}）
        $triggerScript = $this->createTriggerScript($form);
        $subscribeScript = $this->createSubscriberScript($form, function ($builder) {
            // 添加事件响应函数
            $builder->subscribe('group_id', 'select', function ($event) {
                return <<<EOT
       
       function (data) {
                     $('.column4').val('你选择了'+data.text);
                }
EOT;

            });
        });

        $form->scriptinjecter('any_name_but_no_empty', $triggerScript, $subscribeScript);
不起作用

**Comment by zuweie** [comment]
如果使用了Tab的情况，请把$form->scriptinjecter() 这句代码写在任意一个tab里面。具体情况请看更新的文档。
