### ISSUE TITLE
请问可以支持table内input的捕获吗？

### ISSUE THREAD

**Issue by Damon-Shen** [zuweie/FieldInteraction#13]
RT

**Comment by zuweie** [comment]
table 是啥？是 form->tab 这个函数么

**Comment by Damon-Shen** [comment]
$form->table('extra', function ($table) {
    $table->text('key');
    $table->text('value');
    $table->text('desc');
});
是这个，其实和form->hasmany差不多

**Comment by zuweie** [comment]
https://laravel-admin.org/ 你能不能帮我这官方文档找一这个 form->table 的出处吗？我实在找不到，不知道如添加支持～～

**Comment by zuweie** [comment]
https://laravel-admin.org/docs/zh/model-form-fields#model-form-tab 你说的是这个么？如果是这个的话，我的插件已经支持，你只要在其中tab中注入脚本即可，详情请看我的文档

**Comment by Damon-Shen** [comment]
https://laravel-admin.org/docs/zh/model-form-fields#table
