### ISSUE TITLE
表单提交,验证失败后返回页面不会触发控件事件

### ISSUE THREAD

**Issue by Nxir** [zuweie/FieldInteraction#5]
一级分类下不会显示"图标"控件
![image](https://user-images.githubusercontent.com/5908020/55946754-d2474980-5c7f-11e9-9628-4ceaaa661508.png)

三级分类下会显示"图标"控件
![image](https://user-images.githubusercontent.com/5908020/55946960-3407b380-5c80-11e9-82fd-3c92760276fc.png)

现在我选择一级分类,排序字段故意不填写值,提交后将会报错.
这时 选择栏为一级分类,但显示了"图标"控件

![image](https://user-images.githubusercontent.com/5908020/55947066-65807f00-5c80-11e9-819a-e3ad649a60a4.png)

代码如下
```JavaScript
$subscribeScript = $this->createSubscriberScript($form, function($builder){
            $builder->subscribe('type', 'select', function($event) {
                return <<< EOT
                    function (data) {
                        console.log(data);
                        if (data.id == 1 || data.id == 2) { // 如果是一二级分类,隐藏图标控件
                            $('input.icon').parents('.form-group').hide();
                        } else {
                            $('input.icon').parents('.form-group').show();
                        }
                    }
EOT;
            });
        });
```

**Comment by zuweie** [comment]
修复中。。。

**Comment by zuweie** [comment]
请稍后

**Comment by zuweie** [comment]
兄弟，我尝试了很多次，实在是重现不了。不好意思。你可以在当下页面的  <script data-exec-on-popstate> 标签里面 debug 一下。谢谢。
