### ISSUE TITLE
安装完使用报异常

### ISSUE THREAD

**Issue by linkimfly** [zuweie/FieldInteraction#7]
环境：
laravel:5.5.*
laravel-admin:1.6.15

使用如下
```php
$form = new Form(new Student);

$form->text('column5', 'text');

$trigger_script = $this->createTriggerScript($form);

$subscriber_script = $this->createSubscriberScript($form, function($builder) {

	// 监听column5的input事件
	$builder->subscribe('column5', 'input', function ($event) {
		return <<< EOT
   
			function (data) {
			  $('.column5').val(data);
			}
		   
EOT;
	});
});
$form->scriptinjecter('name_no_care', $trigger_script, $subscriber_script);
return $form;
```
报错如下
> Array to string conversion (View: /Users/xxx/Data/wwwroot/xxx/vendor/encore/laravel-admin/resources/views/form.blade.php)

把$form->scriptinjecter  注释掉就没问题，

**Comment by kylin0702** [comment]
我用laravel-admin1.6.13的版本正常,升级到16.15就遇到和你一样的问题

**Comment by kylin0702** [comment]
找了一天终于找到问题,因为larave-admin 新版本Admin::script()写法有写改变,如果是16.15的话,
把**ScriptInjecter.php** 文件的 
`return Admin::script($script_output);`
改为`Admin::script($script_output);`
就可以了.

**Comment by linkimfly** [comment]
@kylin0702 嗯，我前几天已经发现了，解决了！

**Comment by zuweie** [comment]
https://github.com/z-song/laravel-admin/issues/3428 看这个

**Comment by zuweie** [comment]
已经解决。谢谢。请更新最新版
